---
# tasks file for apache
---
  - name: Install apache (https)
    yum:
      name: httpd
      state: installed

  - name: custom index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: enable apache (httpd)
    service:
      name: httpd
      enabled: yes

  - name: start apache (httpd)
    service:
      name: httpd
      state: started

...

